version: '3.1'
services:
  db:
    image: mysql
    container_name: moryggan-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moryggan-db
    ports:
      - "3306:3306"